---
- name: Install and configure Grafana with Prometheus datasource
  hosts: all
  become: yes

  tasks:
    - name: Install Grafana APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Grafana package
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Configure Grafana admin credentials
      blockinfile:
        path: /etc/grafana/grafana.ini
        block: |
          [security]
          admin_user = admin
          admin_password = admin
      notify: Restart Grafana

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Wait for Grafana API to be ready
      uri:
        url: http://localhost:3000/api/health
        method: GET
        status_code: 200
      register: grafana_health
      retries: 20
      delay: 5
      until: grafana_health.status == 200

    - name: Ensure Grafana credentials work
      uri:
        url: http://localhost:3000/api/user
        user: admin
        password: admin
        force_basic_auth: yes
        method: GET
        status_code: 200
      register: grafana_auth_check
      retries: 5
      delay: 5
      until: grafana_auth_check.status == 200

    - name: Create Prometheus datasource in Grafana
      uri:
        url: http://localhost:3000/api/datasources
        method: POST
        user: admin
        password: admin
        force_basic_auth: yes
        body_format: json
        body:
          name: "Prometheus"
          type: "prometheus"
          url: "http://localhost:9090"
          access: "proxy"
          isDefault: true
        status_code: [200, 409]

    - name: Upload default dashboard to Grafana
      uri:
        url: http://localhost:3000/api/dashboards/db
        method: POST
        user: admin
        password: admin
        force_basic_auth: yes
        body_format: json
        body:
          dashboard:
            id: null
            title: "System Metrics Overview"
            tags: ["aws", "prometheus"]
            timezone: "browser"
            schemaVersion: 16
            version: 0
            panels:
              - title: "CPU Usage (%)"
                type: "graph"
                targets:
                  - expr: "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)"
                    refId: "A"
              - title: "Memory Usage (%)"
                type: "graph"
                targets:
                  - expr: "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
                    refId: "A"
              - title: "Disk Usage (%)"
                type: "graph"
                targets:
                  - expr: "(node_filesystem_size_bytes{fstype!=\"tmpfs\"} - node_filesystem_free_bytes{fstype!=\"tmpfs\"}) / node_filesystem_size_bytes{fstype!=\"tmpfs\"} * 100"
                    refId: "A"
              - title: "Network Traffic (bytes/s)"
                type: "graph"
                targets:
                  - expr: "rate(node_network_receive_bytes_total[2m])"
                    refId: "A"
                  - expr: "rate(node_network_transmit_bytes_total[2m])"
                    refId: "B"
          overwrite: true
        status_code: [200, 409]

  handlers:
    - name: Restart Grafana
      systemd:
        name: grafana-server
        state: restarted
        enabled: yes
